### ISSUE TITLE
Implement testing of markdown documents links

### ISSUE THREAD

**Issue by vivalareda** [ai-cfia/devops#13]
ensure accuracy of the documentation by validating links are valid and do not lead to 404 errors or other issues(typos, bad links, etc)

- All markdown documents in the repository are scanned for links.
- Broken links are identified and reported.
- The testing is integrated into the CI/CD pipeline.

**Comment by ThomasCardin** [comment]
One of the step used in the workflow is failing. Need to be fix

**Comment by ThomasCardin** [comment]
This task is already completed. https://github.com/ai-cfia/github-workflows/blob/main/.github/workflows/workflow-markdown-check.md
