### ISSUE TITLE
Document github-label-creation-script.sh

### ISSUE THREAD

**Issue by vivalareda** [ai-cfia/devops#21]
Missing documentation for new script so need to add it

**Comment by rngadam** [comment]
https://registry.terraform.io/providers/integrations/github/latest/docs/resources/issue_label

**Comment by vivalareda** [comment]
> https://registry.terraform.io/providers/integrations/github/latest/docs/resources/issue_label
do you want me to use terraform as well or leave that up to thomas?

**Comment by rngadam** [comment]
> do you want me to use terraform as well or leave that up to thomas?

Yes, you should use terraform. 

You're mainly in charge of Github while he's busy with setting up on Azure.

BTW, I would prefer that we don't create documentation specific issues. Documentation should be a task included in any new development and issues should not be closed until documentation is provided.

**Comment by vivalareda** [comment]
> > do you want me to use terraform as well or leave that up to thomas?
> 
> 
> 
> Yes, you should use terraform. 
> 
> 
> 
> You're mainly in charge of Github while he's busy with setting up on Azure.
> 
> 
> 
> BTW, I would prefer that we don't create documentation specific issues. Documentation should be a task included in any new development and issues should not be closed until documentation is provided.

ok sounds good just so I understand what the process should be, create script/workflow/whatever get it approved then put documentation and ask for re-review is that right?

**Comment by rngadam** [comment]
> ok sounds good just so I understand what the process should be, create script/workflow/whatever get it approved then put documentation and ask for re-review is that right?

If you're doing a two-step, not re-review, merge the script in so the functionality is there and create a separate PR for the documentation associated to the same issue. but obviously better if you create the doc at the same time.

**Comment by vivalareda** [comment]
> > ok sounds good just so I understand what the process should be, create script/workflow/whatever get it approved then put documentation and ask for re-review is that right?
> 
> If you're doing a two-step, not re-review, merge the script in so the functionality is there and create a separate PR for the documentation associated to the same issue. but obviously better if you create the doc at the same time.

Noted sounds good
