### ISSUE TITLE
Automatically check that all issues are attached to the relevant org-wide project

### ISSUE THREAD

**Issue by rngadam** [ai-cfia/devops#25]
## tracking work

* Any work you are doing should relate to a ticket
  * Can either be 
    * a [Github Issue (OpenSource tasks)](https://github.com/ai-cfia)
      * ensure that every issue is attached to the relevant org-level [Github Projects](https://github.com/orgs/ai-cfia/projects)

**Comment by SonOfLope** [comment]
Duplicate issue. This will be done (and is mentionned in) : https://github.com/ai-cfia/github-workflows/issues/73
