### ISSUE TITLE
As a DevOps, I want to create unit tests for the remove previous image script

### ISSUE THREAD

**Issue by ThomasCardin** [ai-cfia/devops#26]
Create automated test from remove previous image script

**Comment by rngadam** [comment]
Not sure we should be expressing user stories "As a DevOps, ..." for things that aren't really:

> A user story is an informal, general explanation of a software feature written from the perspective of the end user. Its purpose is to articulate how a software feature will provide value to the customer.

 Automated testing ought to be part of any software engineering endeavor (same as documentation and version control). We're making an exception here so we can move this part of the infrastructure in.

**Comment by SonOfLope** [comment]
> Not sure we should be expressing user stories "As a DevOps, ..." for things that aren't really:
> 
> > A user story is an informal, general explanation of a software feature written from the perspective of the end user. Its purpose is to articulate how a software feature will provide value to the customer.
> 
> Automated testing ought to be part of any software engineering endeavor (same as documentation and version control). We're making an exception here so we can move this part of the infrastructure in.

I'd like to clarify the intent behind the phrase "As a DevOps" used in the issue description. The term 'DevOps' in our context, though traditionally a mindset and culture, is being used here to reference the specific responsibilities and needs associated with our operational roles. In essence, I think Thomas's use of "As a DevOps" was not to redefine DevOps as a role, but to pinpoint the scope of the task within our current role-based structure.

The purpose of this phrasing was to provide clarity on who would primarily benefit from the creation of these tests (in this case, team members who are handling the operations and deployment aspects of our projects - the DevOps team). The intent is to identify the primary user or beneficiary of a particular task or feature.

Moreover, I agree with you that automated testing is a fundamental aspect of modern software development and should be ingrained in our workflow. However, I believe Thomas's user story was a pragmatic approach to highlight the specific application of this practice for our operational tasks.

I hope this clarifies our perspective. Furthermore, if there's a belief that our team isn't the primary beneficiary of these tests, this opens an important discussion about the broader application of DevOps practices.

In an ideal scenario, DevOps principles should be embraced by all developers, encompassing not just development but also deployment and operational responsibilities. The notion of a segregated 'DevOps team' handling these aspects in isolation does not fully align with the DevOps mindset, which advocates for a more integrated and collaborative approach between development and operations.

**Comment by rngadam** [comment]
> I'd like to clarify the intent behind the phrase "As a DevOps" used in the issue description. The term 'DevOps' in our context, though traditionally a mindset and culture, is being used here to reference the specific responsibilities and needs associated with our operational roles. In essence, I think Thomas's use of "As a DevOps" was not to redefine DevOps as a role, but to pinpoint the scope of the task within our current role-based structure.

can't disagree with anything you said. my disagreement is with the title presenting this as a user story as testing is builtin to the engineering process; so it's a postponed task. It doesn't create value in itself, it is an artifact of building good software.
