### ISSUE TITLE
As a developper, I would like support for a URL shortener tool

### ISSUE THREAD

**Issue by SonOfLope** [ai-cfia/devops#28]
We are currently facing a challenge in our development pipeline where long URLs in markdown files are causing issues with the 80-character line length rule enforced by our markdown linter.

 We're seeking a script or tool that can automatically shorten URLs in markdown files, ensuring compliance with the line length rule while maintaining readability and functionality of the links. 

The [awesome-url-shortener](https://github.com/738/awesome-url-shortener) GitHub repository has a list of url shortener services and hostable services.

**Comment by rngadam** [comment]
This is not necessary. 

https://github.com/updownpress/markdown-lint/blob/master/rules/013-line-length.md

> This rule has an exception where there is no whitespace beyond the configured line length. This allows you to still include items such as long URLs without being forced to break them in the middle.

From a security practice, it is a bad habit to get users to get into the habit of following shortened links obscured by an external link shortener. Only a link shortener within a domain we control should be trusted. 

https://alpha.canada.ca/ had a link shortener service at some point, we should look into why they didn't pursue it.

**Comment by SonOfLope** [comment]
Since it is handled with an exception to the rule and we dont mind long url, I will close this issue.
