### ISSUE TITLE
Special characters (/) in path breaks build

### ISSUE THREAD

**Issue by rngadam** [ai-cfia/devops#30]
@ThomasCardin a case where the PR is done with the user as a prefix to the issue:

```
Error: buildx failed with: ERROR: invalid tag "ghcr.io/ai-cfia/nachet-frontend:CFIALeronB/issue28-ModelSelection": invalid reference format
```
probably need to strip whatever is before /

_Originally posted by @rngadam in https://github.com/ai-cfia/nachet-frontend/issues/74#issuecomment-1910599567_

**Comment by ThomasCardin** [comment]
This issue should be in the `devops` repository. I will transfer it

**Comment by ThomasCardin** [comment]
This issue is resolve in:

- https://github.com/ai-cfia/devops/pull/27.
- https://github.com/ai-cfia/devops/pull/27/commits/85aaa1f4a5835e44015b0959d63363651fe869c0
