### ISSUE TITLE
As a developer, I want access to a plug-and-play Docker image of our FertiScan PostgreSQL database for local development.

### ISSUE THREAD

**Issue by Endlessflow** [ai-cfia/devops#43]
### Context:
Currently, we have Docker images for the React frontend and Flask backend parts of our FertiScan project. These images are pre-built and stored in our package repository. However, we lack an equivalent solution for the PostgreSQL database component.

This image should include all necessary schemas. The goal is to allow any developer to use Docker Compose files to localy orchestrate all components together efficiently – whether they are working on the frontend, backend or datastore.

### Acceptance Criteria:
- [x] #44
- [x] The Docker image should be configured with all required schemas and initial data needed for local development.
- [x] Developers should be able to connect their local application instances with this containerized database without additional configuration steps.
- [x] Database persistence should be optional through volumes for developers who wish to maintain state between container restarts.

**Comment by SonOfLope** [comment]
@Endlessflow you mention "initial data" : 
> The Docker image should be configured with all required schemas and initial data needed for local development.

Are you aware of where to find this initial data and what does it consist of ?

**Comment by Endlessflow** [comment]
I mostly had in mind the schema. I don't know if we want a testing image that would be populated with mock data or just a fresh instance. If just a fresh instance then yeah I suppose just the schema.

**Comment by SonOfLope** [comment]
remaining criterias will be met when merging  https://github.com/ai-cfia/fertiscan-backend/pull/146

**Comment by SonOfLope** [comment]
Tested and validated in https://github.com/ai-cfia/fertiscan-backend/pull/146
