### ISSUE TITLE
LICENCE vs LICENSE

### ISSUE THREAD

**Issue by rngadam** [ai-cfia/devops#7]
https://github.com/ai-cfia/devops/blob/b650fb48b9ded1bd981239a6dc582484bbe73aa9/github-repository-creation-guide.md?plain=1#L8

![image](https://github.com/ai-cfia/devops/assets/538542/76902a0f-8cdb-42a5-817c-b68c9833f226)

Github uses LICENSE

https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository

**Comment by vivalareda** [comment]
Fixed in PR #8
